apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: att1-may15-1-app
  namespace: ai-rhdh
  finalizers: ["resources-finalizer.argocd.argoproj.io"]
spec:
  project: default
  source:
    path: ./components/att1-may15-1/overlays/development
    repoURL: https://github.com/redhat-appstudio-mjf/att1-may15-1-gitops.git
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: att1-may15-1
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: ai-rhdh
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
