apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  rhtap/gitops: att1-may15-1
  janus-idp.io/tekton: att1-may15-1
  backstage.io/kubernetes-id: att1-may15-1
  backstage.io/kubernetes-namespace: att1-may15-1
  app.kubernetes.io/part-of: att1-may15-1
resources:
  - application-dev.yaml