apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/instance: att1-may15-1
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: att1-may15-1
  name: att1-may15-1
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi
