apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: att1-may15-1-database
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: att1-may15-1-database
  name: att1-may15-1-database
spec:
  ports:
    - port: 
      protocol: TCP
      targetPort: 
  selector:
    app.kubernetes.io/instance: att1-may15-1-database
